# Dockerfile
FROM debian:bookworm

ENV FLASK_APP=geordash
ENV FLASK_OPTS="-h 0.0.0.0 -p 5002"
ENV georchestradatadir=/etc/georchestra
ENV REDISURL=""

# set fixed UID and GID - see github.com/hexops/dockerfile
ARG UID=10000
ARG GID=10001

RUN addgroup --gid ${GID} gaia
RUN adduser --uid ${UID} --disabled-password --home /app --shell /bin/sh --ingroup gaia gunicorn

RUN apt update && \
    apt install -y python3-flask-bootstrap python3-flask python3-celery python3-sqlalchemy \
    python3-psycopg2 python3-owslib python3-jsonpickle python3-redis python3-psutil gunicorn python3-gdal && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/doc && rm -rf /usr/share/man

RUN mkdir /geordash
RUN chown gunicorn:gaia /geordash

USER gunicorn

COPY . /geordash
WORKDIR /geordash
# this is entrypoint for dev
#CMD ["flask", "-A", "geordash", "run", "--debug", "-h", "0.0.0.0", "-p", "5002"]
CMD ["sh", "-c", "python3 -m gunicorn --log-level INFO 'geordash:create_app()'"]
